server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1048576
  max_block_duration: 5m

# Not needed for simple demonstrator (local, monolithic)
# compactor:
#   compaction:
#     block_retention: 72h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
    wal:
      path: /tmp/tempo/wal

# Not needed for simple demonstrator (local, monolithic)
# overrides:
#   defaults:
#     metrics_generator:
#       processors: []
