apiVersion: 1

prune: true

deleteDatasources:
  - name: Mimir
    orgId: 1

datasources:
  - name: Mimir
    orgId: 1
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: false
    editable: true
    version: 1
    jsonData:
      httpMethod: POST
      prometheusType: Mimir
      timeInterval: 15s
