apiVersion: 1

prune: true

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Tempo
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    orgId: 1
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true

  - name: Loki
    orgId: 1
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
